# inherit_from: https://raw.githubusercontent.com/halo/dotfiles/master/dotfiles/rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

# Even on an small screen this works fine.
Metrics/LineLength:
  Max: 130

# Tests and Rake tasks may have long blocks.
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

# The trailing comma prevents brain cells from dying on copy-paste errors.
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

# Top-level class documentation is nice, but cumbersome when starting a new project.
Style/Documentation:
  Enabled: false

# Too early to believe that Ruby 3 is significantly faster with this
Style/FrozenStringLiteralComment:
  Enabled: false
